# Generated by Django 5.2.4 on 2025-07-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('votes', models.ManyToManyField(blank=True, related_name='votes', to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user.profile')),
                ('option1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option1', to='post.option')),
                ('option2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option2', to='post.option')),
            ],
        ),
    ]
